### ISSUE TITLE
Benchmarks in Haddock & README

### ISSUE THREAD

**Issue by saurabhnanda** [bgamari/html-parse#13]
From the haddock description:

> The package targets similar use-cases to the venerable tagsoup library, but is significantly more efficient, achieving parsing speeds of over 50 megabytes per second on modern hardware with and typical web documents.

Would it be possible to include some benchmarks in the Haddock and Github README to put concrete perf numbers around tagsoup vs html-parse?

**Comment by bgamari** [comment]
Saurabh Nanda <notifications@github.com> writes:

> From the haddock description:
>
>> The package targets similar use-cases to the venerable tagsoup
>> library, but is significantly more efficient, achieving parsing
>> speeds of over 50 megabytes per second on modern hardware with and
>> typical web documents.
>
> Would it be possible to include some benchmarks in the Haddock and
> Github README to put concrete perf numbers around tagsoup vs
> html-parse?
>
Sure, I think that can be arranged.

**Comment by bgamari** [comment]
Done in c2d36f08ba01b5612c8f5c235a9f0d7cc31905aa. I will push a new version to Hackage when there are some more substantial changes to release.
