### ISSUE TITLE
The parser should return TagSelfClose instead of TagOpen for void elements

### ISSUE THREAD

**Issue by damhiya** [bgamari/html-parse#15]
Hi.

I found non-standard behaviour when parsing self closing tags.

According to HTML5 standard, closing slash is an optiontal on void elements.
See the following reference.
> https://stackoverflow.com/questions/7366344/do-we-still-need-end-slashes-in-html5

But the `parseTokens` function gives `TagOpen` instead of `TagSelfClose` on void elements without closing slash.

It should be fixed, but I think it's impossible to avoid performance down.

**Comment by bgamari** [comment]
I believe the current behavior is correct. The `parseTokens` function is really a tokenizer. While a void element like `<br>` is semantically self-closing, syntactically it is an opening element. Consequently `parseTokens` will identify it as a `TagOpen`. It would be up to the consumer (e.g. the tree construction logic in `Text.HTML.Tree`) to then identify that this is semantically a void tag.

So, while `parseTokens` appears to be correct, there are indeed two bugs here:

 * `Text.HTML.Tree` appears not to handle void elements properly
 * this really isn't adequately documented

Perhaps you would like to open a PR fixing this?

**Comment by SoonWonMoon** [comment]
Ok, I will try to fix `Text.HTML.Tree`.

Thanks for the reply!

**Comment by bgamari** [comment]
This should be closed by #19.
