### ISSUE TITLE
Text without surrounding elements

### ISSUE THREAD

**Issue by fisx** [bgamari/html-parse#2]
(This may be me being ignorant about the specs.  My apologies if it is.)

```haskell
Text.HTML.Parser> tagStream "outside text"
[]
```

i would have expected:

```haskell
[ContentText "outside text"]
```

Btw, would you accept a pull request with a (highly incomplete) hspec test suite?

**Comment by fisx** [comment]
(the last question is of course hypothetical :-)

**Comment by bgamari** [comment]
> Btw, would you accept a pull request with a (highly incomplete) hspec test suite?

Of course, please write one!
