### ISSUE TITLE
Question: Could you release a new version to support GHC-9.2?

### ISSUE THREAD

**Issue by hw202207** [bgamari/html-parse#21]
Looks like the cabal had been updated but not yet release to hackage. Any plan? Thank you!

**Comment by hw202207** [comment]
nvm. Found work around. 
https://cabal.readthedocs.io/en/3.6/cabal-project.html#specifying-packages-from-remote-version-control-locations

**Comment by slotThe** [comment]
@bgamari I think it would still be nice to have a hackage release with the new bounds

**Comment by bgamari** [comment]
Tony Zorman ***@***.***> writes:

> @bgamari I think it would still be nice to have a hackage release with the new bounds
>
Thanks all; I have pushed a new revision bumping the bounds to Hackage.
