### ISSUE TITLE
Use hpack?

### ISSUE THREAD

**Issue by fisx** [bgamari/html-parse#7]
https://github.com/sol/hpack generates cabal files from `package.yaml`.  It keeps track of exposed modules implicitly (and allows turning modules hidden explicitly) and has package-wide and goal-wide dependency lists and ghc options.

Of course for basic libraries like this, using standard tooling has its own merits.

If you think this is a good idea I can write another PR.

**Comment by bgamari** [comment]
I think I'd prefer to stick with the standard tooling here.
